# Generated by Django 5.0.3 on 2025-11-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0007_subscription_created_at_alter_subscription_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        help_text="e.g. 'Build Muscle Mass'", max_length=255
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one program should be active per user at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("raw_json", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_programs",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField(help_text="1-7 for Mon-Sun")),
                (
                    "day_name",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "focus",
                    models.CharField(
                        help_text="e.g., 'Upper Body Strength', 'Cardio'",
                        max_length=100,
                    ),
                ),
                ("is_rest_day", models.BooleanField(default=False)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="ai_program_generator.aiprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of exercise in the session"
                    ),
                ),
                ("exercise_name", models.CharField(max_length=200)),
                (
                    "sets",
                    models.IntegerField(
                        default=0, help_text="Number of sets (0 if not applicable)"
                    ),
                ),
                (
                    "reps",
                    models.CharField(
                        help_text="Rep scheme or duration (e.g., '3x10', '30 seconds')",
                        max_length=100,
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        help_text="e.g., 'moderate', 'RPE 7-8', 'easy pace'",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Coaching tips or additional info"
                    ),
                ),
                (
                    "program_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="ai_program_generator.programday",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="aiprogram",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_program__user_id_648bbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprogram",
            index=models.Index(
                fields=["user", "is_active"], name="ai_program__user_id_3af21f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programday",
            index=models.Index(
                fields=["program", "day_number"], name="ai_program__program_47d8b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programday",
            unique_together={("program", "day_number")},
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["program_day", "order"], name="ai_program__program_8eefe6_idx"
            ),
        ),
    ]
