import React, { useState } from "react";
import { Container, Row, Col, Card, Button, Modal, Alert } from "react-bootstrap";
import { useAuth } from "../../../context/AuthContext";
import "./AddOns.css";

import img13 from "../../Assets/img13.jpg";
import img14 from "../../Assets/img14.jpg";
import img15 from "../../Assets/img15.jpg";

const premiumAddons = [
  {
    id: "ebook",
    title: "E-Book: Science-Based Training",
    description: "Comprehensive guide.",
    image: img13,
    price: "$29.99",
    details:
      "Expert-written fitness guide covering workout optimization, diet strategies, and scientific insights for peak performance.",
    accessLink: "/ebooks/science-based-training.pdf",
    planKey: "ebook",
  },
  {
    id: "zoom",
    title: "1-on-1 Zoom Consultation With Coach",
    description: "Personalized session.",
    image: img14,
    price: "$49.99",
    details:
      "Discuss goals, training adjustments, and personalized strategies in a live call with a professional coach.",
    planKey: "zoom",
  },
  {
    id: "ai",
    title: "Coach Custom AI Training Plan",
    description: "AI-generated plan.",
    image: img15,
    price: "$99.99",
    details:
      "Get a fully tailored workout and nutrition program generated by AI based on your fitness level and goals.",
    planKey: "ai",
  },
];

const AddOns = ({ addToCart, ownedAddOns = {}, showOwnedOnly = false, plan = "none" }) => {
  const [selectedAddon, setSelectedAddon] = useState(null);
  const [showInfoModal, setShowInfoModal] = useState(false);
  const [infoMessage, setInfoMessage] = useState("");
  const { isAuthenticated, loginWithRedirect } = useAuth();

  // Normalize and automatically grant access for Advanced plan
  const normalizedAddOns = { ...(ownedAddOns || {}) };
  if (plan?.toLowerCase() === "advanced") {
    normalizedAddOns.ebook = Math.max(normalizedAddOns.ebook || 0, 1);
  }

  // Filter after normalization
  const visibleAddons = showOwnedOnly
    ? premiumAddons.filter((a) => (normalizedAddOns[a.id] || 0) > 0)
    : premiumAddons;

  const hasAnyVisible = visibleAddons.length > 0;

  // Purchase (redirect to cart)
  const handlePurchase = (addon) => {
    if (!isAuthenticated) {
      sessionStorage.setItem("redirectAddon", JSON.stringify(addon));
      return loginWithRedirect();
    }
    if (addToCart) addToCart(addon);
    window.location.href = "/cart";
  };

  // Book Now → always redirect to cart
  const handleBookNow = (addon) => {
    if (!isAuthenticated) {
      sessionStorage.setItem("redirectAddon", JSON.stringify(addon));
      return loginWithRedirect();
    }
    if (addToCart) addToCart(addon);
    window.location.href = "/cart";
  };

  // Info modal for purchased add-ons
  const handlePurchasedInfo = (addonId) => {
    if (addonId === "ai") {
      setInfoMessage(
        "Your personalized AI training plan is being prepared. The coach will send you your customized program directly soon."
      );
    } else if (addonId === "zoom") {
      setInfoMessage(
        "Your coach will contact you directly by email to organize your 1-on-1 Zoom session based on your availability."
      );
    } else {
      setInfoMessage("You already have access to this add-on.");
    }
    setShowInfoModal(true);
  };

  return (
    <section id="addons-section" className="addons-section">
      <Container>
        <h2 className="section-titles">Premium Add-Ons</h2>

        {!hasAnyVisible && showOwnedOnly && (
          <Alert variant="info">No purchased add-ons available.</Alert>
        )}

        <Row className="premium-grid">
          {visibleAddons.map((addon) => {
            const owned = (normalizedAddOns[addon.id] || 0) > 0;

            return (
              <Col lg={4} md={6} sm={12} key={addon.id} className="d-flex justify-content-center">
                <Card className="addon-card">
                  <Card.Img src={addon.image} className="addon-image" />
                  <Card.Body>
                    <Card.Title>{addon.title}</Card.Title>
                    <Card.Text>{addon.description}</Card.Text>
                    <span className="premium-price">{addon.price}</span>

                    <div className="addon-buttons">
                      <Button variant="info" onClick={() => setSelectedAddon(addon)}>
                        Learn More
                      </Button>

                      {owned ? (
                        addon.id === "ebook" ? (
                          <Button
                            variant="primary"
                            href={addon.accessLink}
                            target="_blank"
                            title={
                              plan === "advanced"
                                ? "Included in your Advanced Plan"
                                : "Access your purchased E-Book"
                            }
                          >
                            Access
                          </Button>
                        ) : (
                          <Button
                            variant="secondary"
                            onClick={() => handlePurchasedInfo(addon.id)}
                          >
                            Purchased
                          </Button>
                        )
                      ) : (
                        <Button
                          variant="success"
                          onClick={() =>
                            addon.id === "ebook" ? handlePurchase(addon) : handleBookNow(addon)
                          }
                          disabled={showOwnedOnly}
                        >
                          {addon.id === "ebook" ? "Purchase" : "Book Now"}
                        </Button>
                      )}
                    </div>
                  </Card.Body>
                </Card>
              </Col>
            );
          })}
        </Row>

        {/* Add-On Details Modal */}
        <Modal show={!!selectedAddon} onHide={() => setSelectedAddon(null)} centered>
          <Modal.Header closeButton>
            <Modal.Title>{selectedAddon?.title}</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <p>{selectedAddon?.details}</p>
            <h4 className="addon-price">{selectedAddon?.price}</h4>
          </Modal.Body>
        </Modal>

        {/* Info Modal for Purchased Add-ons */}
        <Modal show={showInfoModal} onHide={() => setShowInfoModal(false)} centered>
          <Modal.Header closeButton>
            <Modal.Title>Purchased Add-On</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <p>{infoMessage}</p>
          </Modal.Body>
          <Modal.Footer>
            <Button variant="primary" onClick={() => setShowInfoModal(false)}>
              OK
            </Button>
          </Modal.Footer>
        </Modal>
      </Container>
    </section>
  );
};

export default AddOns;
