import React, { useState } from "react";
import { Container, Row, Col, Card, Button, Modal } from "react-bootstrap";
import "./AddOns.css";
import img13 from "../../Assets/img13.jpg";
import img14 from "../../Assets/img14.jpg";
import img15 from "../../Assets/img15.jpg";
import img16 from "../../Assets/img16.jpg";
import img17 from "../../Assets/img17.jpg";

const premiumAddons = [
  { title: "E-Book: Science-Based Training", description: "Comprehensive guide.", image: img13, price: "$29.99", details: "Expert-written fitness guide covering workout optimization, diet strategies, and scientific insights for peak performance." },
  { title: "1-on-1 Zoom Consultation", description: "Personalized session.", image: img14, price: "$49.99", details: "Discuss goals, training adjustments, and personalized strategies in a live call with a professional coach." },
  { title: "Coach Custom AI Training Plan", description: "AI-generated plan.", image: img15, price: "$99.99", details: "Get a fully tailored workout and nutrition program generated by AI based on your fitness level and goals." },
  { title: "In-Person Private Coaching", description: "Exclusive private session.", image: img16, price: "$199.99", details: "Receive hands-on coaching, real-time feedback, and technique correction to maximize your performance." },
  { title: "Exclusive Coaching Group", description: "Access workouts & mentorship.", image: img17, price: "$29.99", details: "Join a private community with guided workouts, live Q&A sessions, and direct mentorship from elite trainers." }
];

const AddOns = ({ addToCart }) => {
  const [selectedAddon, setSelectedAddon] = useState(null);

  return (
    <section className="addons-section">
      <Container>
        <h2 className="section-title">Premium Add-Ons</h2>
        <Row className="premium-grid">
          {premiumAddons.map((addon, index) => (
            <Col lg={4} md={6} sm={12} key={index} className="d-flex justify-content-center">
              <Card className="addon-card">
                <Card.Img src={addon.image} className="addon-image" />
                <Card.Body>
                  <Card.Title>{addon.title}</Card.Title>
                  <Card.Text>{addon.description}</Card.Text>
                  <span className="premium-price">{addon.price}</span>
                  <div className="addon-buttons">
                    <Button variant="info" className="learn-more-btn" onClick={() => setSelectedAddon(addon)}>Learn More</Button>
                    <Button variant="success" className="purchase-btn" onClick={() => addToCart(addon)}>Purchase</Button>
                  </div>
                </Card.Body>
              </Card>
            </Col>
          ))}
        </Row>

        {/* Add-On Details Modal */}
        <Modal show={!!selectedAddon} onHide={() => setSelectedAddon(null)} centered>
          <Modal.Header closeButton>
            <Modal.Title>{selectedAddon?.title}</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <p>{selectedAddon?.details}</p>
            <h4 className="addon-price">{selectedAddon?.price}</h4>
            <Button variant="success" onClick={() => {
              addToCart(selectedAddon);
              setSelectedAddon(null);
            }}>Purchase</Button>
          </Modal.Body>
        </Modal>
      </Container>
    </section>
  );
};

export default AddOns;
