import React, { useState } from "react";
import { Container, Row, Col, Card, Button, Modal } from "react-bootstrap";
import { useAuth } from "../../../context/AuthContext"; // ← same as Plans.js
import Booking from "../../Shared/Booking/Booking";
import "./AddOns.css";

import img13 from "../../Assets/img13.jpg";
import img14 from "../../Assets/img14.jpg";
import img15 from "../../Assets/img15.jpg";

// Simulated purchase tracking (replace with backend logic later)
const purchasedAddOns = new Set();

const premiumAddons = [
  {
    id: "ebook",
    title: "E-Book: Science-Based Training",
    description: "Comprehensive guide.",
    image: img13,
    price: "$29.99",
    details:
      "Expert-written fitness guide covering workout optimization, diet strategies, and scientific insights for peak performance.",
    accessLink: "/ebooks/science-based-training.pdf",
    planKey: "ebook",
  },
  {
    id: "zoom",
    title: "1-on-1 Zoom Consultation",
    description: "Personalized session.",
    image: img14,
    price: "$49.99",
    details:
      "Discuss goals, training adjustments, and personalized strategies in a live call with a professional coach.",
    isBookable: true,
    planKey: "zoom",
  },
  {
    id: "ai-plan",
    title: "Coach Custom AI Training Plan",
    description: "AI-generated plan.",
    image: img15,
    price: "$99.99",
    details:
      "Get a fully tailored workout and nutrition program generated by AI based on your fitness level and goals.",
    isBookable: true,
    planKey: "ai-plan",
  },
];

const AddOns = ({ addToCart }) => {
  const [selectedAddon, setSelectedAddon] = useState(null);
  const [showBooking, setShowBooking] = useState(false);
  const [selectedBookingAddon, setSelectedBookingAddon] = useState(null);

  const { isAuthenticated, loginWithRedirect, fetchWithAuth } = useAuth(); // ← updated to match Plans.js

  const handlePurchase = async (addon) => {
    if (!isAuthenticated) {
      sessionStorage.setItem("redirectAddon", JSON.stringify(addon)); // Restore after login
      return loginWithRedirect(); // ← same as Plans.js
    }

    // Simulate purchase
    purchasedAddOns.add(addon.id);
    console.log("Purchased Add-On:", addon.title);

    if (addToCart) addToCart(addon); // Optional
    window.location.href = "/cart"; // Redirect after purchase
  };

  const handleBookNow = async (addon) => {
    if (!isAuthenticated) {
      sessionStorage.setItem("redirectAddon", JSON.stringify(addon));
      return loginWithRedirect(); // ← consistent
    }

    setSelectedBookingAddon(addon);
    setShowBooking(true);
  };

  return (
    <section id="addons-section" className="addons-section">
      <Container>
        <h2 className="section-title">Premium Add-Ons</h2>
        <Row className="premium-grid">
          {premiumAddons.map((addon, index) => (
            <Col lg={4} md={6} sm={12} key={index} className="d-flex justify-content-center">
              <Card className="addon-card">
                <Card.Img src={addon.image} className="addon-image" />
                <Card.Body>
                  <Card.Title>{addon.title}</Card.Title>
                  <Card.Text>{addon.description}</Card.Text>
                  <span className="premium-price">{addon.price}</span>
                  <div className="addon-buttons">
                    <Button variant="info" onClick={() => setSelectedAddon(addon)}>Learn More</Button>

                    {addon.id === "ebook" ? (
                      purchasedAddOns.has(addon.id) ? (
                        <Button variant="primary" href={addon.accessLink} target="_blank">
                          Access
                        </Button>
                      ) : (
                        <Button variant="success" onClick={() => handlePurchase(addon)}>
                          Purchase
                        </Button>
                      )
                    ) : (
                      <Button variant="success" onClick={() => handleBookNow(addon)}>
                        Book Now
                      </Button>
                    )}
                  </div>
                </Card.Body>
              </Card>
            </Col>
          ))}
        </Row>

        {/* Add-On Details Modal */}
        <Modal show={!!selectedAddon} onHide={() => setSelectedAddon(null)} centered>
          <Modal.Header closeButton>
            <Modal.Title>{selectedAddon?.title}</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <p>{selectedAddon?.details}</p>
            <h4 className="addon-price">{selectedAddon?.price}</h4>
          </Modal.Body>
        </Modal>

        {/* Booking Modal */}
        {showBooking && (
          <Booking
            onClose={() => setShowBooking(false)}
            addToCart={addToCart}
            addon={selectedBookingAddon}
          />
        )}
      </Container>
    </section>
  );
};

export default AddOns;
