# Generated by Django 5.0.3 on 2025-03-15 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auth0_id", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("coach", "Coach")],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("basic", "Basic"),
                            ("advanced", "Advanced"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("basic", "Basic"), ("advanced", "Advanced")],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certifications", models.TextField()),
                ("experience_years", models.IntegerField()),
                ("specialties", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("height_cm", models.IntegerField()),
                ("weight_kg", models.FloatField()),
                (
                    "fitness_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "primary_goal",
                    models.CharField(
                        choices=[
                            ("muscle_gain", "Muscle Gain"),
                            ("fat_loss", "Fat Loss"),
                            ("endurance", "Endurance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "workout_frequency",
                    models.CharField(
                        choices=[
                            ("1-2x per week", "1-2 times a week"),
                            ("3-4x per week", "3-4 times a week"),
                            ("5+ per week", "5+ times a week"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "daily_activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary (Minimal movement)"),
                            ("lightly_active", "Lightly Active (Some movement daily)"),
                            ("active", "Active (Frequent physical activity)"),
                            ("very_active", "Very Active (Intense training or labor)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sleep_hours", models.IntegerField()),
                ("body_fat_percentage", models.FloatField(blank=True, null=True)),
                (
                    "body_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ectomorph", "Ectomorph (Lean & Slim)"),
                            ("mesomorph", "Mesomorph (Athletic & Muscular)"),
                            ("endomorph", "Endomorph (Broad & Higher Fat Storage)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
