# Generated by Django 5.0.3 on 2025-10-15 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('ebook', 'E-Book'), ('zoom', 'Zoom Consultation'), ('ai', 'AI Training Plan')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='users.user')),
            ],
            options={
                'db_table': 'users_addons',
                'ordering': ['-start_date'],
            },
        ),
    ]
