# Generated by Django 5.0.3 on 2025-10-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_ons',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
