# Generated by Django 5.0.3 on 2025-10-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_coachbooking_coachtrainingprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachtrainingprogress',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterField(
            model_name='coachtrainingprogress',
            name='addon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to='users.addon'),
        ),
        migrations.AlterField(
            model_name='coachtrainingprogress',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ai_clients', to='users.user'),
        ),
        migrations.AlterField(
            model_name='coachtrainingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainings', to='users.user'),
        ),
        migrations.DeleteModel(
            name='CoachBooking',
        ),
    ]
